logging:
  level:
    root: error

spring:
  application:
    name: batch
  profiles:
    active: local
  batch:
    job:
      name: ${job.name:NONE}
    jdbc:
      table-prefix: boot3_batch_

  # spring cloud task ????? ?? ?? ?? off
  cloud:
    task:
      initialize-enabled: false
      table-prefix: boot3_task_