logging:
  level:
    root: info

spring:
  datasource:
    url: jdbc:mysql://mysql-db:3306/scdf?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&autoReconnect=true
    username: user
    password: user
    driver-class-name: org.mariadb.jdbc.Driver