services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: scdf
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      JDK_JAVA_OPTIONS: '-Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8'
    ports:
      - '3306:3306'
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --lower_case_table_names=1

networks:
  scdf-network:
    name: scdf-network
    driver: bridge